development:
  adapter: mysql2
  encoding: utf8
  database: shop
  pool: 5
  username: root
  password: 
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  database: shop
  pool: 5
  username: root
  password: 
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  database: shop
  pool: 5
  username: root
  password: 
  host: localhost